apiVersion: v1
kind: Pod
metadata:
  labels:
    ci: rsb-public-build
spec:
  containers:
  - name: rpooli-build
    image: registry.openanalytics.eu/openanalytics/rpooli-build:J-11_R-4.1
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "2Gi"
        cpu: "2000m"
    command:
    - cat
    tty: true
