apiVersion: v1
kind: Pod
metadata:
  labels:
    ci: rsb-public-build
spec:
  containers:
  - name: rpooli-build
    image: 196229073436.dkr.ecr.eu-west-1.amazonaws.com/openanalytics/rpooli-build
    resources:
      limits:
        memory: "2Gi"
        cpu: "2000m"
      requests:
        memory: "1.5Gi"
        cpu: "1000m"
    command:
    - cat
    tty: true
