<?xml version="1.0" encoding="UTF-8"?>
<!--
    R Service Bus
    
    Copyright (c) Copyright of OpenAnalytics BVBA, 2010-2011
 
    ===========================================================================
 
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
 
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.
 
    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>
        
    @author rsb.development@openanalytics.eu
-->
<definitions name="RsbMtomJobs" targetNamespace="http://soap.rsb.openanalytics.eu/jobs"
    xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:jobs="http://soap.rsb.openanalytics.eu/jobs"
    xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:types="http://soap.rsb.openanalytics.eu/types"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <types>
        <schema targetNamespace="http://soap.rsb.openanalytics.eu/jobs"
            xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://soap.rsb.openanalytics.eu/types"
                schemaLocation="../schemas/soap-types.xsd" />
        </schema>
    </types>

    <message name="JobRequest">
        <part name="job" element="types:job" />
    </message>
    <message name="JobResponse">
        <part name="result" element="types:result" />
    </message>

    <portType name="MtomJobProcessor">
        <operation name="Process">
            <input message="jobs:JobRequest" name="JobRequest" />
            <output message="jobs:JobResponse" name="JobResponse" />
        </operation>
    </portType>

    <binding name="MtomJobProcessorSoapBinding" type="jobs:MtomJobProcessor">
        <soap12:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <operation name="Process">
            <soap12:operation soapAction="" style="document" />
            <input name="JobRequest">
                <soap12:body use="literal" />
            </input>
            <output name="JobResponse">
                <soap12:body use="literal" />
            </output>
        </operation>
    </binding>

    <service name="MtomJobService">
        <port name="MtomJobProcessorPort" binding="jobs:MtomJobProcessorSoapBinding">
            <soap12:address location="http://provided_by_mule" />
        </port>
    </service>
</definitions>